## Упражнения по библиотеке Numpy

In [7]:
import numpy as np
from random import random, randint

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [6]:
arr = np.random.randint(0, 12, 20)
print("Original array: ", arr)

condition = (arr > 3) & (arr < 8)
indexes = np.where(condition)[0]
values = arr[condition]

print("Indexes meeting condition: ", indexes)
print("Values meeting condition: ", values)

arr[condition] = -values

print("Modified array: ", arr)

Original array:  [ 4  9  7  6  2  0  3  8  3  7  0  8  6  0  9  1  5  6 10 11]
Indices meeting condition:  [ 0  2  3  9 12 16 17]
Values meeting condition:  [4 7 6 7 6 5 6]
Modified array:  [-4  9 -7 -6  2  0  3  8  3 -7  0  8 -6  0  9  1 -5 -6 10 11]


**2.** Заменить максимальный элемент случайного массива на 0

In [9]:
arr =  np.random.randint(1, 200,20)
print(arr)
arr[arr.argmax()]=0
print (arr)

[ 39  61 144  61 106   5 144 150  14 136   8  52  36  58  73  15   2  33
  17 183]
[ 39  61 144  61 106   5 144 150  14 136   8  52  36  58  73  15   2  33
  17   0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [12]:
arr1 = np.random.randint(0, 5, 2)
arr2 = np.random.randint(5, 10, 2)

print(arr1)
arr = [
    arr1,
    arr2
]
print(arr)
print(grid := np.meshgrid(*arr))
result = np.stack(grid, axis=-1).reshape(-1, len(arr))
print(result)

[2 0]
[array([2, 0]), array([7, 6])]
[array([[2, 0],
       [2, 0]]), array([[7, 7],
       [6, 6]])]
[[2 7]
 [0 7]
 [2 6]
 [0 6]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [17]:
B = np.random.randint(0, 10, [2,2])
A = np.random.randint(0, 10, [8,3])
print(A)
print(B)

result = []
for i, row_a in enumerate(A):
    set_a = set(row_a)
    for row_b in B:
        if set(row_b).issubset(set_a):
            result.append(i)
            break

print("A indexes:", result)

[[4 0 4]
 [7 1 5]
 [5 5 4]
 [9 9 3]
 [8 0 1]
 [4 4 5]
 [9 4 4]
 [7 5 6]]
[[7 5]
 [6 6]]
A indexes: [1, 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [25]:

A = np.random.randint(0, 2, [10, 3])
print(A)

unique = np.array([len(np.unique(row)) for row in A])

res_ind = np.where(unique>1)[0]
res_rows = A[unique>1]

print("\nIndexes of diff rows:", res_ind)

print("\nResult:\n", res_rows)

[[0 0 0]
 [1 1 0]
 [1 0 1]
 [0 0 0]
 [1 0 1]
 [1 1 1]
 [0 0 0]
 [1 0 1]
 [1 1 1]
 [0 1 0]]

Indexes of diff rows: [1 2 4 7 9]

Result:
 [[1 1 0]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [0 1 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [21]:
size = np.random.randint(2,10)
A = np.random.randint(0, 2, [size,size])
print(A)

unique = np.array([len(np.unique(row)) for row in A])

res_ind = np.where(unique>1)[0]
res_rows = A[unique>1]

print("\nIndexes of diff rows:", res_ind)

print("\nResult:\n", res_rows)

[[1 0 1]
 [1 0 0]
 [1 1 1]]

Indexes of diff rows: [0 1]

Result:
 [[1 0 1]
 [1 0 0]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [29]:


size_i = np.random.randint(2, 5)
size_j = np.random.randint(5, 8)
A = np.random.randint(0, 7, [size_i, size_j])

print(A)

dgn_elem = np.diag(A)

non_zero = dgn_elem[dgn_elem != 0]

product = np.prod(non_zero) if len(non_zero) > 0 else 0

print("Diagonal:", dgn_elem)
print("Not null: ", non_zero)
print("Res:", product)




n=randint(2,5)
m =randint(5,8)
B = [[ randint(0,7) for _ in range(m)]for _ in range(n)]
print(B)

res = 1
for i in range(n):
    for j in range(m):
        if(i==j and B[i][j]!=0):
            res*=B[i][j]


print("Res:\n", res)


[[3 1 2 0 2 0]
 [0 6 4 4 1 3]
 [2 0 1 0 0 4]]
Diagonal: [3 6 1]
Not null:  [3 6 1]
Res: 18
[[1, 3, 0, 4, 2], [1, 4, 1, 4, 7], [1, 2, 2, 4, 7], [4, 1, 0, 6, 2], [6, 7, 4, 3, 2]]
Res:
 96


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [11]:
size = randint(1, 5)
A1= np.array([randint(0, 5) for _ in range(size)])
print(A1)
A2 = np.array([randint(0, 5) for _ in range(size)])
print(A2)
res = False
res= np.array_equal(np.sort(A1), np.sort(A2))

print( "Res: ", res)



size=randint(1,5)
B1 = [ randint(0,5) for _ in range(size)]
print(B1)
B2 = [ randint(0,5) for _ in range(size)]
print(B2)
res = False
res = sorted(B1) == sorted(B2)

print("Res: ", res)

[5 5]
[4 2]
Res:  False
[5, 1, 0, 4, 2]
[1, 5, 3, 2, 4]
Res:  False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [9]:
size = randint(2, 15)
A = np.array([randint(0, 7) for _ in range(size)])
print(A)

zero_ind = np.where(A[:-1] == 0)[0]
print(zero_ind)
following_zero = A[zero_ind + 1]
print(following_zero)

res = np.max(following_zero) if len(following_zero) > 0 else 0
print("Res: ", res)



size=randint(2,15)
B = [ randint(0,7) for _ in range(size)]
max = 0
print(B)
i=1
for (i) in range(len(B)):
    if max<i and B[i-1]==0:
        max=B[i]

print("Res: ",max)

[1 7 0 0 4 4 4 0 7 6]
[2 3 7]
[0 4 7]
Res:  7
[3, 1, 0, 3, 1, 7]
Res:  3


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [35]:
size=randint(2,15)
B = [ randint(0,7) for _ in range(size)]
print(B)
values = []
lengths = []
current_val = B[0]  
count = 1           
for val in B[1:]:   
    if val == current_val:
        count += 1  
    else:
        values.append(current_val)  
        lengths.append(count)      
        current_val = val          
        count = 1                  
values.append(current_val)  
lengths.append(count)       
print("Res: ", values, lengths)

[7, 0, 4, 6, 7, 6, 2, 3, 3, 6]
Res:  [7, 0, 4, 6, 7, 6, 2, 3, 6] [1, 1, 1, 1, 1, 1, 1, 2, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [160]:
# your code

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [13]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [20]:
avg_ccal_other = np.mean(calorie_stats)
#print(avg_ccal_other)

crunchie_munchies_ccal = 60

average_calories = avg_ccal_other - crunchie_munchies_ccal

print(average_calories)

106.88311688311688
46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [26]:
calorie_stats_sorted=np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [36]:
median_calories = np.median(calorie_stats)

print("median: ",median_calories)

average_calories_competitors = np.mean(calorie_stats)
print(f"avg: {average_calories_competitors}")

median:  110.0
avg: 106.88311688311688


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

110.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [30]:
more_than_60 = np.sum(calorie_stats > 60)

more_calories = (more_than_60 / len(calorie_stats)) * 100

print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [32]:
calorie_std = np.std(calorie_stats)

print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
# your code